[package]
name = "birdie"
version = "0.1.0"
edition = "2021"
description = "Experimenting with Shuttle"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
rocket = "0.5.0-rc.1"
shuttle-service = { version = "0.2", features = ["web-rocket"] }
