[package]
name = "birdie"
version = "0.1.0"
edition = "2021"
description = "Experimenting with Shuttle"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres"] }
shuttle-service = { version = "0.2", features = ["sqlx-postgres", "web-rocket"] }
