[package]
name = "birdie"
version = "0.1.0"
edition = "2021"
description = "Split group expenses using the minimal number of transactions"
license = "GPL-3.0-or-later"
repository = "https://github.com/jming422/birdie.git"
include = ["/*", "!/js/", "!/frontend/", "!.*"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
axum = "0.5"
chrono = { version = "0.4", features = ["serde"] }
flate2 = { version = "1.0" }
log = "0.4"
serde = "1.0"
shuttle-service = { version = "0.3", features = ["sqlx-postgres", "web-axum"] }
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres", "decimal", "chrono"] }
sync_wrapper = "0.1"
tar = { version = "0.4" }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.3", features = ["fs"] }
